### ISSUE TITLE
Install failed: at Zlib._binding.onerror (zlib.js:296:17)

### ISSUE THREAD

**Issue by SamuelMarks** [apiaryio/swagger2blueprint#12]
```
sm@Sof:~$ node --version
v0.10.40
sm@Sof:~$ npm install -g swagger2blueprint
 
> robotskirt@2.7.1 install /home/sm/n/lib/node_modules/swagger2blueprint/node_modules/fury/node_modules/robotskirt
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:296:17)
gyp ERR! System Linux 3.19.0-26-generic
gyp ERR! command "node" "/home/sm/n/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sm/n/lib/node_modules/swagger2blueprint/node_modules/fury/node_modules/robotskirt
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
 
> protagonist@0.20.1 install /home/sm/n/lib/node_modules/swagger2blueprint/node_modules/fury/node_modules/drafter/node_modules/protagonist
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:296:17)
gyp ERR! System Linux 3.19.0-26-generic
gyp ERR! command "node" "/home/sm/n/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sm/n/lib/node_modules/swagger2blueprint/node_modules/fury/node_modules/drafter/node_modules/protagonist
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! robotskirt@2.7.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotskirt@2.7.1 install script.
npm ERR! This is most likely a problem with the robotskirt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls robotskirt
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-26-generic
npm ERR! command "/home/sm/n/bin/node" "/home/sm/n/bin/npm" "install" "-g" "swagger2blueprint"
npm ERR! cwd /home/sm
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYC
```

**Comment by pksunkara** [comment]
Unfortunately, this is not an issue in our code but rather issue in your environment. Can you try upgrading `npm` to 2.0 and try this again?

**Comment by SamuelMarks** [comment]
```
sm@Sof:~$ npm --version
2.14.2
sm@Sof:~$ node --version
v0.10.40
sm@Sof:~$ npm install -g swagger2blueprint
|
> robotskirt@2.7.1 install /home/sm/n/lib/node_modules/swagger2blueprint/node_modules/fury/node_modules/robotskirt
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: socket hang up
gyp ERR! stack     at createHangUpError (http.js:1473:15)
gyp ERR! stack     at CleartextStream.socketCloseListener (http.js:1523:23)
gyp ERR! stack     at CleartextStream.emit (events.js:117:20)
gyp ERR! stack     at tls.js:694:10
gyp ERR! stack     at process._tickCallback (node.js:448:13)
gyp ERR! System Linux 3.19.0-26-generic
gyp ERR! command "node" "/home/sm/n/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sm/n/lib/node_modules/swagger2blueprint/node_modules/fury/node_modules/robotskirt
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
 
> protagonist@0.20.1 install /home/sm/n/lib/node_modules/swagger2blueprint/node_modules/fury/node_modules/drafter/node_modules/protagonist
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: socket hang up
gyp ERR! stack     at SecurePair.error (tls.js:1011:23)
gyp ERR! stack     at EncryptedStream.CryptoStream._done (tls.js:703:22)
gyp ERR! stack     at CleartextStream.read [as _read] (tls.js:499:24)
gyp ERR! stack     at CleartextStream.Readable.read (_stream_readable.js:341:10)
gyp ERR! stack     at EncryptedStream.onCryptoStreamFinish (tls.js:304:47)
gyp ERR! stack     at EncryptedStream.g (events.js:180:16)
gyp ERR! stack     at EncryptedStream.emit (events.js:117:20)
gyp ERR! stack     at finishMaybe (_stream_writable.js:360:12)
gyp ERR! stack     at endWritable (_stream_writable.js:367:3)
gyp ERR! stack     at EncryptedStream.Writable.end (_stream_writable.js:345:5)
gyp ERR! System Linux 3.19.0-26-generic
gyp ERR! command "node" "/home/sm/n/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sm/n/lib/node_modules/swagger2blueprint/node_modules/fury/node_modules/drafter/node_modules/protagonist
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.19.0-26-generic
npm ERR! argv "node" "/home/sm/n/bin/npm" "install" "-g" "swagger2blueprint"
npm ERR! node v0.10.40
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! robotskirt@2.7.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotskirt@2.7.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the robotskirt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls robotskirt
npm ERR! There is likely additional logging output above.
```

**Comment by SamuelMarks** [comment]
Strangely enough I just tried with `git clone` followed by `npm install`, and was able to run it from `index.js`.

:)

Still a few issues (like with quoting, it's showing `&#39;` instead of `'`), but it's good enough :+1:

**Comment by pksunkara** [comment]
> like with quoting, it's showing `&#39;` instead of `'`

Can you please create an issue with an example?
